### ISSUE TITLE
build error in mingw64

### ISSUE THREAD

**Issue by sailfish009** [libfirm/libfirm#17]
$ make
...
LINK build/debug/libfirm.so
build/debug/ir/common/timing.o: In function `_time_get':
C:\msys64\work\libfirm/ir/common/timing.c:134: undefined reference to `__imp_timeGetTime'
build/debug/ir/stat/statev.o: In function `key_matches':
C:\msys64\work\libfirm/ir/stat/statev.c:41: undefined reference to `regexec'
build/debug/ir/stat/statev.o: In function `stat_ev_begin':
C:\msys64\work\libfirm/ir/stat/statev.c:198: undefined reference to `regcomp'
build/debug/ir/stat/statev.o: In function `stat_ev_end':
C:\msys64\work\libfirm/ir/stat/statev.c:218: undefined reference to `regfree'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:154: build/debug/libfirm.so] Error 1

And here is fix:

vi Makefile +55
LINKFLAGS += $(LINKFLAGS_$(variant)) -lm **-lwinmm -lregex**

**Comment by johannes-bucher** [comment]
Thank you! This is now fixed.
