### ISSUE TITLE
No target triple is recognized

### ISSUE THREAD

**Issue by ghost** [libfirm/libfirm#18]
I created a custom backend using the provided template. While it compiles properly I am unable to invoke it. If I just call it the error message tells me it is looking for my-target-gcc, which it can not find.
If I try to provide the target triple itself it can also not find it.
This is also true for existing backends.

I wasn't able to find any guide or docs for this. Could you help me understand how to get this to work?

Thanks.

**Comment by UniQP** [comment]
You have two options:
1. If you just want to generate an assembly file, you can use `cparser -integrated-cpp -target <targetTriple> -S <inputFile>`.
2. You can create a symlink `my-target-gcc` to a `gcc` that can handle the assembly format generated by your backend. This allows you to directly generate an executable.

**Comment by ghost** [comment]
Thank you very much. Building only the assembly is all I need.
