### ISSUE TITLE
Do tarvals have limits? Where are these limits described?

### ISSUE THREAD

**Issue by Qix-** [libfirm/libfirm#21]
Just playing around with some introductory examples. In my parser, I don't parse numeric constants beyond their tokens and elect keep them as strings, which is great because `new_integer_tarval_from_str()` exists.

Doing a simple `tarval_sub()` and then `tarval_is_negative()` tends to work fine - except for when the tarval is really long.

The following program outputs `0` when it really should output `1` (smaller values correctly show `1`):

```c++
extern "C" {
#include "./libfirm/include/libfirm/firm.h"
}

#include <cassert>
#include <iostream>

int main() {
	ir_init();

	ir_tarval *a = new_integer_tarval_from_str("10", 2, 0, 10, mode_Is);
	assert(a != get_tarval_bad());
	ir_tarval *b = new_integer_tarval_from_str("37465772635463726354918273645536475", 35, 0, 10, mode_Is);
	assert(b != get_tarval_bad());
	ir_tarval *c = tarval_sub(a, b);
	assert(c != get_tarval_bad());
	std::cout << tarval_is_negative(c) << std::endl;
	return 0;
}
```
```
0
```

Am I missing something, or is there a limit in tarval length? Shouldn't I be getting `get_tarval_bad()` here (and thus a failed assertion)? Do tarvals overflow?

Commit is 6dabd82983e8a42960484880c88f194346830d30.

**Comment by Qix-** [comment]
Also, I'm following https://pp.ipd.kit.edu/~firm/tutorial/index.html but it appears `new_Const` has been removed. It used to take `ir_tarval*` values, creating nodes out of them - but now I can't figure out how to get an `ir_tarval*` to an `ir_node*`.

What's the new method without having to convert to a `long` first?

**Comment by Qix-** [comment]
Ah okay - `target_set_wrap_on_overflow(1)` is the default - setting it to `0` correctly causes the assertion to trigger.

**Comment by Qix-** [comment]
Ah. These functions are generated and placed in `gen` >.> Sorry for the noise.

**Comment by johannes-bucher** [comment]
The tarval computation functions wrap integer values on overflow by default.
If you want to change that behavior, the `void tarval_set_wrap_on_overflow(int wrap_on_overflow)` function can be used.

In your example, calling `tarval_set_wrap_on_overflow(0)` beforehand will result in what you expected - the assertion for tarval b will fail.

The limits which are considered for tarval wrapping and overflowing are defined by the mode you specify when creating the tarval.
