### ISSUE TITLE
Homepage URL Broken

### ISSUE THREAD

**Issue by rdebath** [libfirm/libfirm#6]
http://libfirm.org/ redirects to a 404.

**Comment by MatzeB** [comment]
Works for me right now, maybe the webserver had a hiccup.
Are you landing on: http://pp.ipd.kit.edu/firm/ ?

**Comment by rdebath** [comment]
Ah, I see. I've got the "SSL Enforcer" plugin Like EFF's [HTTPS Everywhere](https://www.eff.org/https-everywhere) So I'll slightly retract.

The URL http://pp.ipd.kit.edu/firm/  exists but unlike the rest of https://pp.ipd.kit.edu/ the URLs under https://pp.ipd.kit.edu/firm/  do not exist.

If I blacklist  https://pp.ipd.kit.edu/ it works fine.
Note: The website as a whole is okay on SSL, the certificate is valid (even though it uses SHA-1 which the browsers no longer like) and the rest of the website seems to be complete.

**Comment by MatzeB** [comment]
Yeah some of the "subdirectories" are missing in the https configuration on that server. I'll ping someone about it.
